### Question 1

Create a NumPy array arr of integers from 0 to 5 and print its data type.


In [2]:
import numpy as np
arr = np.arange(6)
print(arr.dtype)

int32


### Question 2

Given a NumPy array arr, check if its data type is float64.


In [3]:
arr = np.array([1.0, 2.0])
print(arr.dtype == np.float64)

True


### Question 3

Create a NumPy array arr with a data type of complex128 containing three complex numbers.


In [4]:
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)

[1.+2.j 3.+4.j 5.+6.j]


### Question 4

Convert an existing NumPy array arr of integers to float32 data type.


In [5]:
arr = np.array([1, 2, 3])
arr = arr.astype(np.float32)
print(arr.dtype)

float32


### Question 5

Given a NumPy array arr with float64 data type, convert it to float32 to reduce decimal precision.


In [6]:
arr = np.array([1.1, 2.2, 3.3], dtype=np.float64)
arr = arr.astype(np.float32)
print(arr.dtype)

float32


### Question 6

Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.


In [7]:
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype
print(array_attributes(np.array([[1,2],[3,4]])))

((2, 2), 4, dtype('int32'))


### Question 7

Create a function array_dimension that returns the dimensionality of a NumPy array.


In [8]:
def array_dimension(arr):
    return arr.ndim
print(array_dimension(np.array([[1],[2]])))

2


### Question 8

Design a function item_size_info that returns the item size and total size in bytes of a NumPy array.


In [9]:
def item_size_info(arr):
    return arr.itemsize, arr.nbytes
print(item_size_info(np.array([1,2,3])))

(4, 12)


### Question 9

Create a function array_strides that returns the strides of the given NumPy array.


In [10]:
def array_strides(arr):
    return arr.strides
print(array_strides(np.array([[1,2],[3,4]])))

(8, 4)


### Question 10

Design a function shape_stride_relationship that returns the shape and strides of the given array.


In [11]:
def shape_stride_relationship(arr):
    return arr.shape, arr.strides
print(shape_stride_relationship(np.array([[1,2],[3,4]])))

((2, 2), (8, 4))


### Question 11

Create a function create_zeros_array(n) to return a NumPy array of zeros with n elements.


In [12]:
def create_zeros_array(n):
    return np.zeros(n)
print(create_zeros_array(5))

[0. 0. 0. 0. 0.]


### Question 12

Write a function create_ones_matrix(rows, cols) to create a 2D array filled with ones.


In [13]:
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))
print(create_ones_matrix(2,3))

[[1. 1. 1.]
 [1. 1. 1.]]


### Question 13

Write a function generate_range_array(start, stop, step) to create a ranged NumPy array.


In [14]:
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)
print(generate_range_array(0,10,2))

[0 2 4 6 8]


### Question 14

Design a function generate_linear_space(start, stop, num) for equally spaced values.


In [15]:
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)
print(generate_linear_space(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


### Question 15

Create a function create_identity_matrix(n) using numpy.eye.


In [16]:
def create_identity_matrix(n):
    return np.eye(n)
print(create_identity_matrix(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Question 16

Write a function that converts a Python list into a NumPy array.


In [17]:
def list_to_array(lst):
    return np.array(lst)
print(list_to_array([1,2,3]))

[1 2 3]


### Question 17

Create a NumPy array and use numpy.view() to create a new view with the same data.


In [18]:
arr = np.array([1,2,3,4])
view_arr = arr.view()
print(view_arr)

[1 2 3 4]


### Question 18

Write a function to concatenate two NumPy arrays along a specified axis.


In [19]:
def concat_arrays(a,b,axis):
    return np.concatenate((a,b),axis=axis)
print(concat_arrays(np.array([[1,2]]),np.array([[3,4]]),0))

[[1 2]
 [3 4]]


### Question 19

Concatenate two arrays with different shapes horizontally using numpy.concatenate.


In [20]:
a = np.array([[1],[2]])
b = np.array([[3,4],[5,6]])
print(np.concatenate((a,b),axis=1))

[[1 3 4]
 [2 5 6]]


### Question 20

Vertically stack multiple arrays from a list using numpy.vstack.


In [21]:
arrays = [np.array([1,2]), np.array([3,4])]
print(np.vstack(arrays))

[[1 2]
 [3 4]]


### Question 21

Write a function to generate an array of integers within a specified range (inclusive) with a step.


In [22]:
def gen_array_range(start, stop, step):
    return np.arange(start, stop+1, step)
print(gen_array_range(1,5,1))

[1 2 3 4 5]


### Question 22

Generate 10 equally spaced values between 0 and 1 using NumPy.


In [23]:
print(np.linspace(0,1,10))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


### Question 23

Create 5 logarithmically spaced values between 1 and 1000.


In [24]:
print(np.logspace(0,3,5))

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


### Question 24

Create a Pandas DataFrame from a NumPy array with 5 rows and 3 columns of random integers (1-100).


In [25]:
import pandas as pd
df = pd.DataFrame(np.random.randint(1,101,size=(5,3)))
print(df)

    0   1   2
0  68  56  16
1  52  70  28
2  33  14  64
3  30  98  46
4  14  77  30


### Question 25

Write a function to replace all negative values in a specific column with zeros using NumPy.


In [26]:
def replace_neg(df,col):
    df[col] = np.where(df[col]<0,0,df[col])
    return df
print(replace_neg(pd.DataFrame({'A':[-1,2]}),'A'))

   A
0  0
1  2


### Question 26

Access the 3rd element from the given NumPy array.


In [27]:
arr = np.array([1,2,3,4])
print(arr[2])

3


### Question 27

Retrieve the element at index (1, 2) from a 2D array.


In [28]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[1,2])

6


### Question 28

Extract elements greater than 5 using boolean indexing.


In [29]:
arr = np.array([1,6,3,7])
print(arr[arr>5])

[6 7]


### Question 29

Slice elements from index 2 to 5 (inclusive) from a NumPy array.


In [30]:
arr = np.array([0,1,2,3,4,5])
print(arr[2:6])

[2 3 4 5]


### Question 30

Slice the sub-array [[2, 3], [5, 6]] from a 2D array.


In [31]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[:,1:3])

[[2 3]
 [5 6]]


### Question 31

Extract elements based on indices from a 2D array.


In [32]:
arr = np.array([[1,2],[3,4]])
print(arr[[0,1],[1,0]])

[2 3]


### Question 32

Filter elements greater than a threshold using boolean indexing.


In [33]:
arr = np.array([1,5,8])
print(arr[arr>4])

[5 8]


### Question 33

Extract specific elements from a 3D array using separate index arrays.


In [34]:
arr = np.arange(27).reshape(3,3,3)
print(arr[[0,1],[1,2],[2,0]])

[ 5 15]


### Question 34

Return elements satisfying two boolean conditions.


In [35]:
arr = np.array([1,5,10,15])
print(arr[(arr>4)&(arr<12)])

[ 5 10]


### Question 35

Extract elements from a 2D array using separate row and column index arrays.


In [36]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[[0,1,2],[2,1,0]])

[3 5 7]


### Question 36

Add scalar 5 to every element of an array using broadcasting.


In [37]:
arr = np.array([1,2,3])
print(arr+5)

[6 7 8]


### Question 37

Multiply each row of a (3, 4) array by corresponding elements of a (1, 3) array.


In [38]:
a = np.ones((3,4))
b = np.array([[1],[2],[3]])
print(a * b)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]


### Question 38

Add a (1, 4) array to every row of a (4, 3) array using broadcasting.


In [39]:
a = np.ones((4,3))
b = np.ones((1,3))
print(a + b)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


### Question 39

Add two arrays of shapes (3, 1) and (1, 3) using broadcasting.


In [40]:
a = np.ones((3,1))
b = np.ones((1,3))
print(a + b)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


### Question 40

Handle shape incompatibility during multiplication between (2, 3) and (2, 2) arrays.


In [41]:
a = np.ones((2,3))
b = np.ones((2,2))
try:
 print(a*b)
except ValueError as e:
 print(e)

operands could not be broadcast together with shapes (2,3) (2,2) 


### Question 41

Calculate column-wise mean of a 2D array.


In [42]:
arr = np.array([[1,2],[3,4]])
print(arr.mean(axis=0))

[2. 3.]


### Question 42

Find maximum value in each row.


In [43]:
arr = np.array([[1,2],[3,4]])
print(arr.max(axis=1))

[2 4]


### Question 43

Find indices of maximum values in each column.


In [44]:
arr = np.array([[1,4],[3,2]])
print(arr.argmax(axis=0))

[1 0]


### Question 44

Apply a custom function to compute moving sum along rows.


In [45]:
arr = np.array([[1,2,3],[4,5,6]])
print(np.cumsum(arr,axis=1))

[[ 1  3  6]
 [ 4  9 15]]


### Question 45

Check if all elements in each column are even.


In [46]:
arr = np.array([[2,4],[6,8]])
print((arr%2==0).all(axis=0))

[ True  True]


### Question 46

Reshape a given array into dimensions m x n.


In [47]:
arr = np.arange(6)
print(arr.reshape(2,3))

[[0 1 2]
 [3 4 5]]


### Question 47

Return a flattened version of a given matrix.


In [48]:
arr = np.array([[1,2],[3,4]])
print(arr.flatten())

[1 2 3 4]


### Question 48

Concatenate two arrays along a specified axis.


In [49]:
a = np.array([[1,2]])
b = np.array([[3,4]])
print(np.concatenate((a,b),axis=0))

[[1 2]
 [3 4]]


### Question 49

Split an array into sub-arrays along a specified axis.


In [53]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
result = np.split(arr, 2, axis=1)
print(result)


[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


### Question 50

Insert and delete elements at specified indices from an array.


In [54]:
arr = np.array([1,2,3])
arr = np.insert(arr,1,10)
arr = np.delete(arr,2)
print(arr)

[ 1 10  3]


### Question 51

Perform element-wise addition between two arrays.


In [55]:
a = np.array([1,2])
b = np.array([3,4])
print(a+b)

[4 6]


### Question 52

Perform element-wise subtraction: subtract arr2 from arr1.


In [56]:
a = np.array([5,6])
b = np.array([2,1])
print(a-b)

[3 5]


### Question 53

Perform element-wise multiplication.


In [57]:
a = np.array([2,3])
b = np.array([4,5])
print(a*b)

[ 8 15]


### Question 54

Divide elements of arr1 by arr2 element-wise.


In [58]:
a = np.array([8,9])
b = np.array([2,3])
print(a/b)

[4. 3.]


### Question 55

Perform element-wise exponentiation: arr1 ** arr2.


In [59]:
a = np.array([2,3])
b = np.array([3,2])
print(a**b)

[8 9]


### Question 56

Count occurrences of a substring in a string array.


In [60]:
arr = np.array(['abc','ababc'])
print(np.char.count(arr,'ab'))

[1 2]


### Question 57

Extract uppercase characters from a string array.


In [61]:
arr = np.array(['Hello','WORLD'])
print(np.char.upper(arr))

['HELLO' 'WORLD']


### Question 58

Replace substring occurrences with another string in a string array.


In [62]:
arr = np.array(['abc','ababc'])
print(np.char.replace(arr,'ab','xy'))

['xyc' 'xyxyc']


### Question 59

Concatenate strings in a NumPy array element-wise.


In [63]:
a = np.array(['a','b'])
b = np.array(['c','d'])
print(np.char.add(a,b))

['ac' 'bd']


### Question 60

Find the length of the longest string in a string array.


In [64]:
arr = np.array(['abc','abcdef'])
print(np.vectorize(len)(arr).max())

6


### Question 61

Generate 100 random integers (1–1000) and compute mean, median, variance, and std deviation.


In [65]:
arr = np.random.randint(1,1001,100)
print(arr.mean(), np.median(arr), arr.var(), arr.std())

524.47 537.0 78194.7691 279.633276095675


### Question 62

Generate 50 random numbers (1–100) and compute the 25th and 75th percentiles.


In [66]:
arr = np.random.randint(1,101,50)
print(np.percentile(arr,25), np.percentile(arr,75))

26.5 82.0


### Question 63

Compute correlation coefficient between two arrays using np.corrcoef.


In [67]:
a = np.random.rand(10)
b = np.random.rand(10)
print(np.corrcoef(a,b))

[[1.         0.11739139]
 [0.11739139 1.        ]]


### Question 64

Perform matrix multiplication using np.dot.


In [68]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.dot(a,b))

[[19 22]
 [43 50]]


### Question 65

Compute the 10th, 50th, and 90th percentiles and quartiles for an array of 50 integers.


In [69]:
arr = np.random.randint(1,101,50)
print(np.percentile(arr,[10,50,90]))

[25.8 48.  88. ]


### Question 66

Find index of a specific element in an array.


In [70]:
arr = np.array([1,2,3])
print(np.where(arr==2))

(array([1], dtype=int64),)


### Question 67

Sort a random array in ascending order.


In [71]:
arr = np.random.randint(1,10,5)
print(np.sort(arr))

[3 5 7 8 9]


### Question 68

Filter elements greater than 20.


In [72]:
arr = np.array([10,30,20])
print(arr[arr>20])

[30]


### Question 69

Filter elements divisible by 3.


In [73]:
arr = np.array([3,4,9,10])
print(arr[arr%3==0])

[3 9]


### Question 70

Filter elements between 20 and 40 (inclusive).


In [74]:
arr = np.array([10,25,30,45])
print(arr[(arr>=20)&(arr<=40)])

[25 30]


### Question 71

Check byte order of a NumPy array using dtype.byteorder.


In [75]:
arr = np.array([1])
print(arr.dtype.byteorder)

=


### Question 72

Perform in-place byte swapping using byteswap().


In [76]:
arr = np.array([1],dtype='>i4')
arr.byteswap(True)
print(arr)

[16777216]
